### ISSUE TITLE
Captcha changed?

### ISSUE THREAD

**Issue by talwrii** [acheong08/OpenAIAuth#3]
I seem to be getting a captcha in a different format. Which is resulting in this error (I'm running tag: 0.0.6 as source code).

I'm getting an error like

```
Traceback (most recent call last):
  File "/usr/local/bin/llmchat", line 33, in <module>
    sys.exit(load_entry_point('large-language-model-cli', 'console_scripts', 'llmchat')())
  File "/Users/tomwright/mine/llmcli/llmcli/__init__.py", line 101, in chatgpt_main
    chatgpt(args)
  File "/Users/tomwright/mine/llmcli/llmcli/__init__.py", line 171, in chatgpt
    chat = chatgpt_login(SESSION_FILE, credentials)
  File "/Users/tomwright/mine/llmcli/llmcli/__init__.py", line 228, in chatgpt_login
    chat = Chatbot(config=credentials)
  File "/Users/tomwright/mine/revchatgpt/ChatGPT/src/revChatGPT/revChatGPT.py", line 95, in __init__
    self.refresh_session()
  File "/Users/tomwright/mine/revchatgpt/ChatGPT/src/revChatGPT/revChatGPT.py", line 340, in refresh_session
    raise exc
  File "/Users/tomwright/mine/revchatgpt/ChatGPT/src/revChatGPT/revChatGPT.py", line 337, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/Users/tomwright/mine/revchatgpt/ChatGPT/src/revChatGPT/revChatGPT.py", line 373, in login
    raise exc
  File "/Users/tomwright/mine/revchatgpt/ChatGPT/src/revChatGPT/revChatGPT.py", line 366, in login
    auth.begin()
  File "/Users/tomwright/mine/revchatgpt/OpenAIAuth/src/OpenAIAuth/OpenAIAuth.py", line 97, in begin
    raise Exception("API error")
Exception: API error
```

The headers look like this:

```
{'Alt-Svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Cf-Chl-Bypass': '1', 'Cf-Ray': 'XXXXXXXXXX-LHR', 'Content-Encoding': 'gzip', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Sun, 11 Dec 2022 22:04:57 GMT', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Permissions-Policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()', 'Referrer-Policy': 'same-origin', 'Server': 'cloudflare', 'Set-Cookie': 'XXXXXXXXXXXXXXXXXXXXX path=/; expires=Sun, 11-Dec-22 22:34:57 GMT; domain=.chat.openai.com; HttpOnly; Secure; SameSite=None', 'Vary': 'Accept-Encoding', 'X-Frame-Options': 'SAMEORIGIN'}
```

The page looks like this:

```
#  ![](/favicon.ico) chat.openai.com

##  Checking if the site connection is secure
```
When I logged in with a browser I was prompted by a capture with a similar tittle. J

**Comment by acheong08** [comment]
This seems to belong to cloudflare. This hasn't been reversed yet

**Comment by acheong08** [comment]
> Hey, I might have a stab at reverse engineering cloudflare at the weekend 

I don't think it is feasible at the moment to reverse engineer cloudflare. They use up to 25 challenges/fingerprints which are impossible to spoof headlessly. As of now, the only solution is to use an actual puppet browser to obtain the `cf_clearance`. They also added reCaptcha to the third step which requires some change. That can be bypassed via a paid service like 2Captcha but so far, no way to easily bypass it yet. 

You can check out https://github.com/dessant/buster if you have an azure subscription and use the Voice to Text model for bypass. There are some scripts you would need to write to find and automate the use of that browser extension though.
