### ISSUE TITLE
Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

### ISSUE THREAD

**Issue by deathsovushka** [acheong08/OpenAIAuth#44]
```
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\ChatGPT\main.py", line 91, in <module>
    access_token = auth.get_access_token()
  File "C:\Users\user\PycharmProjects\ChatGPT\venv\lib\site-packages\OpenAIAuth.py", line 69, in get_access_token
    return self.__part_two()
  File "C:\Users\user\PycharmProjects\ChatGPT\venv\lib\site-packages\OpenAIAuth.py", line 82, in __part_two
    return self.__part_three(code_verifier, url)
  File "C:\Users\user\PycharmProjects\ChatGPT\venv\lib\site-packages\OpenAIAuth.py", line 97, in __part_three
    return self.__part_four(code_verifier, state)
  File "C:\Users\user\PycharmProjects\ChatGPT\venv\lib\site-packages\OpenAIAuth.py", line 124, in __part_four
    return self.__part_five(code_verifier, state)
  File "C:\Users\user\PycharmProjects\ChatGPT\venv\lib\site-packages\OpenAIAuth.py", line 150, in __part_five
    return self.__part_six(code_verifier, location, url)
  File "C:\Users\user\PycharmProjects\ChatGPT\venv\lib\site-packages\OpenAIAuth.py", line 179, in __part_six
    return self.__get_access_token(code_verifier, resp.headers["Location"])
  File "C:\Users\user\PycharmProjects\ChatGPT\venv\lib\site-packages\OpenAIAuth.py", line 221, in __get_access_token
    raise Exception("{}: {}".format(error, error_description))
Exception: access_denied: Your version of the ChatGPT app is out of date. Please update to the newest build of the app.
```

**Comment by zutto** [comment]
openai changed their apple authentication flow to require new pre-auth with their services before going to auth0, so use access tokens, or https://github.com/acheong08/OpenAIAuth/pull/45 until permanent fix is in place.

**Comment by acheong08** [comment]
I got a temporary fix in for the Go version. Might need some annoying workarounds for python

**Comment by acheong08** [comment]
Apologize for the slow action. Caught a high fever over the past week

**Comment by acheong08** [comment]
Looks like I missed some details from #45. Device ID expires
