### ISSUE TITLE
OpenAIAuth.__init__() got an unexpected keyword argument 'cf_clearance'

### ISSUE THREAD

**Issue by edbighead** [acheong08/OpenAIAuth#6]
Getting the following error, probably related to https://github.com/acheong08/OpenAIAuth/commit/cfb9a17bb4138ce05fd63cde53c685c5381b6a1a

```
Traceback (most recent call last):
  File "/code/project/slack.py", line 16, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/code/project/slack.py-ggXW00PY/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
    self.refresh_session()
  File "/code/project/slack.py-ggXW00PY/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 352, in refresh_session
    raise exc
  File "/code/project/slack.py-ggXW00PY/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 349, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/code/project/slack.py-ggXW00PY/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 375, in login
    auth = OpenAIAuth(email, password, use_proxy=bool(
TypeError: OpenAIAuth.__init__() got an unexpected keyword argument 'cf_clearance'
```

**Comment by acheong08** [comment]
You have to set cf_clearance now. It's due to https://github.com/acheong08/ChatGPT/issues/261#issuecomment-1346019919

**Comment by edbighead** [comment]
> You have to set cf_clearance now. It's due to [acheong08/ChatGPT#261 (comment)](https://github.com/acheong08/ChatGPT/issues/261#issuecomment-1346019919)

set where exactly?

**Comment by acheong08** [comment]
In the config: See https://github.com/acheong08/ChatGPT/wiki/Setup

**Comment by edbighead** [comment]
> In the config: See https://github.com/acheong08/ChatGPT/wiki/Setup

thanks, wasn't following the development during the weekend. Looks like cookie is the only available auth for now
